baseURL: "https://rasulashiqur.github.io/"
title: Ashiqur Rasul
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
  twitter: SamiaKabir12

taxonomies:
  tag: tags

menu:
  main:
    - name: Projects
      url: /projects/
      weight: 1
    - name: Publication
      url: /papers/
      weight: 2
    - name: Teaching
      url: /courses/
      weight: 3
    - name: News
      url: /news/
      weight: 4
    # - name: Archive
    #   url: /archive/
    #   weight: 5

params:
  description: "I'm a first year Ph.D. student in Electrical and Computer Engineering at Georgia Institute of Technology. My research interest lies at the intersection of ML algorithm and effcient ML hardware design. I am currently a part of the Low-power, Adaptive and Resilient Systems Lab (LARS) at Georgia Tech, working under the supervision of [Dr. Abhijit Chatterjee](https://ece.gatech.edu/directory/abhijit-chatterjee)."
  author: Ashiqur Rasul
  # googleAnalyticsID: ""
  DateFormat: "January 2006"
  defaultTheme: dark
  hideFooter: true
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  profileMode:
    enabled: true
    title: Ashiqur Rasul
    subtitle: "Hello! This is Ashiqur! I'm a 1st year Ph.D. student in Electrical and Computer Engineering at Georgia Institute of Technology. My research interest lies at the intersection of ML algorithm, efficient ML hardware design and neuromorphic computing in both analog and digital domain.
     I am currently a part of Low-power, Adaptive and Resilient Systems Lab (LARS) at Georgia Tech,
     working under the supervision of [Dr. Abhijit Chatterjee](https://ece.gatech.edu/directory/abhijit-chatterjee).

     <br><br>
     My research projects at Georgia Tech involves exploring the exciting areas of hardware-software codesign - input adaptive algorithm for efficient machine learning and analog or digital hardware design exploration for this purpose. 
     We work in collaboration with prominent semiconductor companies such Intel, Texas Instruments and research organizations like Semiconductor Research Corporation (SRC).   

     <br><br>
     Before coming to Purdue, I completed my Bachelor's degree from Bangladesh University of Engineering and Technology (BUET) and went to Notre Dame College, Dhaka, Bangladesh.
     When I am not in-front of the computer screen, I maybe playing soccer, roaming around or crossing off another item on my bucket list.

     <br> <br>

     I am looking for internship positions in hardware design for summer 26. I will be happy to connect with you!"
    imageUrl: "/picture.jpg"
    imageWidth: 180
    imageHeight: 180
    imageTitle: Ashiqur Rasul
    buttons:
      - name: Projects
        url: /projects/
      - name: Publication
        url: /papers/
      - name: Teaching
        url: /courses/
      - name: News
        url: /news/

  socialIcons:
    - name: CV
      url: "/resume.pdf"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/samia-kabir/"
    - name: Google Scholar
      url: "https://scholar.google.com/citations?user=DZ5jg-IAAAAJ&hl=en"
    - name: GitHub
      url: "https://github.com/AshiqurRasul"
    - name: Email
      url: "mailto:arasul6@gatech.edu"

  assets:
    disableHLJS: true
    disableScrollBarStyle: true
  cover:
    hiddenInList: true
    hiddenInSingle: true
  label:
    text: "Ashiqur Rasul"
    icon: /favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: xcode
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
